# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('day', models.DateTimeField()),
                ('image', models.ImageField(upload_to=b'')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('studentid', models.IntegerField(max_length=20)),
                ('password', models.IntegerField(max_length=40)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
