# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='auth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=10),
        ),
    ]
