# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='day',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
