# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='follow',
        ),
    ]
