# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='push_number',
            field=models.IntegerField(default=0),
        ),
    ]
