# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 11:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180129_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='follow',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, b'UNDERGRADUATE'), (1, b'MBA'), (2, b'UD_STUDENT_COUNCIL'), (3, b'MBA_STUDENT_COUNCIL'), (4, b'CLASS_A'), (5, b'CLASS_B'), (6, b'CLASS_C'), (7, b'CLASS_D'), (8, b'CLASS_E'), (9, b'KUBS_CLUB'), (10, b'KUBS_SOCIETY'), (11, b'ALUMNI')], default=0, max_length=25),
        ),
    ]
