# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180210_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='represent',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
