# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_push_push_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
