# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_student_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
