# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180210_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='number',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='represent',
            field=models.CharField(default=99, max_length=200),
        ),
    ]
