# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180214_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
