# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20180214_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
