# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20180215_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
